### ISSUE TITLE
请问在mpvue小程序里引入 全局拦截 wx api 该如何做 

### ISSUE THREAD

**Issue by dave-wind** [bigmeow/minapp-api-promise#1]
```
现在是引入毫无反应

**Comment by bigmeow** [comment]
文档有说明。。。很清楚，还有提问的艺术，什么代码也不贴我也不知道你什么问题。
另外注意，用了该拦截后，如果你还用 `wx.request`肯定是没法拦截的，只能用`wxp.request`，注意主语
