### ISSUE TITLE
希望能增加对commonjs模块支持

### ISSUE THREAD

**Issue by tim0991** [bigmeow/minapp-api-promise#2]
加入了`expose-loader`之后, `WXP.default` 可以正常使用
但是我希望是可以省略掉`.defualt`直接使用WXP

**Comment by bigmeow** [comment]
我的`webpack.config.js `里有这样一个配置`libraryTarget: 'umd'`, 把它换成  cmd 试试？

**Comment by youngjuning** [comment]
https://github.com/youngjuning/wxPromise 了解一下，互换 star、fork

**Comment by Accusr** [comment]
配置intercept 中config.header 无效
